// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA--k01WWxHMCKrQlS65mcaqSzfMhR90M',
    appId: '1:890412545511:web:0840a38d2847b2e1d9b942',
    messagingSenderId: '890412545511',
    projectId: 'f-club-management',
    authDomain: 'f-club-management.firebaseapp.com',
    databaseURL: 'https://f-club-management-default-rtdb.firebaseio.com',
    storageBucket: 'f-club-management.appspot.com',
    measurementId: 'G-S2RPTHQR7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoryUDM28qngptBqm7ujk-GTfq6sHXSBo',
    appId: '1:890412545511:android:74f43e3213ca80e0d9b942',
    messagingSenderId: '890412545511',
    projectId: 'f-club-management',
    databaseURL: 'https://f-club-management-default-rtdb.firebaseio.com',
    storageBucket: 'f-club-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFbrQJUI3jv-_aaLxIW3OH5QqxUGGycRU',
    appId: '1:890412545511:ios:99ed3cf7cff2deb5d9b942',
    messagingSenderId: '890412545511',
    projectId: 'f-club-management',
    databaseURL: 'https://f-club-management-default-rtdb.firebaseio.com',
    storageBucket: 'f-club-management.appspot.com',
    androidClientId: '890412545511-9vgt9hvaopoo0pl46qfaa9k0nouq4iel.apps.googleusercontent.com',
    iosClientId: '890412545511-guv5nfefu6gbik9op0n29j7j0iichd36.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFbrQJUI3jv-_aaLxIW3OH5QqxUGGycRU',
    appId: '1:890412545511:ios:99ed3cf7cff2deb5d9b942',
    messagingSenderId: '890412545511',
    projectId: 'f-club-management',
    databaseURL: 'https://f-club-management-default-rtdb.firebaseio.com',
    storageBucket: 'f-club-management.appspot.com',
    androidClientId: '890412545511-9vgt9hvaopoo0pl46qfaa9k0nouq4iel.apps.googleusercontent.com',
    iosClientId: '890412545511-guv5nfefu6gbik9op0n29j7j0iichd36.apps.googleusercontent.com',
    iosBundleId: 'com.example.swdProject',
  );
}
